"""AutoScout24-Taxonomie: Ausstattungs-IDs, Gruppen, Karosserie-Mapping.

Automatisch generiert aus __NEXT_DATA__.taxonomy (siehe docs/as24-taxonomy.json).
"""

from __future__ import annotations

# Karosserie-Slug (unser Modell) -> AutoScout24 body-Parameter-ID
BODY_TYPE_TO_AS24 = {
    "kleinwagen": 1,
    "cabrio": 2,
    "coupe": 3,
    "suv": 4,
    "kombi": 5,
    "limousine": 6,
    "van": 12,
}

# Türen-Slug -> (doorfrom, doorto)
DOORS_TO_AS24 = {"2/3": (2, 3), "4/5": (4, 5)}

# Alle Ausstattungsmerkmale: ID -> Label
EQUIPMENT = {
    1: "ABS",
    2: "Fahrerairbag",
    3: "Beifahrerairbag",
    4: "Schiebedach",
    5: "Klimaanlage",
    6: "Lederausstattung",
    10: "Radio",
    11: "Allrad",
    12: "Servolenkung",
    13: "Elektrische Fensterheber",
    15: "Alufelgen",
    16: "Elektrische Sitze",
    17: "Zentralverriegelung",
    18: "Alarmanlage",
    19: "Nebelscheinwerfer",
    20: "Anhängerkupplung",
    21: "teilb. Rücksitzbank",
    23: "Navigationssystem",
    25: "Winterreifen",
    26: "Wegfahrsperre",
    27: "Dachreling",
    28: "Tuning",
    29: "Katalysator",
    30: "Klimaautomatik",
    31: "Traktionskontrolle",
    32: "Seitenairbag",
    34: "Sitzheizung",
    36: "Behindertengerecht",
    38: "Tempomat",
    39: "Xenonscheinwerfer",
    40: "Einparkhilfe",
    41: "Bordcomputer",
    42: "ESP",
    43: "MP3",
    44: "Windschott (für Cabrio)",
    45: "Airbag hinten",
    46: "Kopfairbag",
    47: "Zentralverriegelung mit Funkfernbedienung",
    48: "Rechtslenker",
    50: "Panoramadach",
    52: "Standheizung",
    54: "Getönte Scheiben",
    111: "Taxi oder Mietwagen",
    112: "Sportpaket",
    113: "Start/Stop-Automatik",
    114: "Multifunktionslenkrad",
    115: "Tagfahrlicht",
    116: "Sportfahrwerk",
    117: "Sportsitze",
    118: "Kurvenlicht",
    119: "Skisack",
    121: "Elektrische Seitenspiegel",
    122: "Bluetooth",
    123: "Head-up display",
    124: "Freisprecheinrichtung",
    125: "Isofix",
    126: "Lichtsensor",
    127: "Regensensor",
    128: "Einparkhilfe Sensoren vorne",
    129: "Einparkhilfe Sensoren hinten",
    130: "Einparkhilfe Rückfahrkamera",
    131: "Einparkhilfe selbstlenkendes System",
    132: "CD",
    133: "Abstandstempomat",
    134: "Armlehne",
    135: "Beheizbare Frontscheibe",
    136: "Beheizbares Lenkrad",
    137: "Berganfahrassistent",
    138: "DAB-Radio",
    139: "Elektrische Heckklappe",
    140: "LED-Scheinwerfer",
    141: "LED-Tagfahrlicht",
    142: "Lederlenkrad",
    143: "Lordosenstütze",
    144: "Luftfederung",
    145: "Massagesitze",
    146: "Müdigkeitswarnsystem",
    147: "Nachtsicht-Assistent",
    148: "Notbremsassistent",
    149: "Notrufsystem",
    150: "Reifendruckkontrollsystem",
    151: "Schaltwippen",
    152: "Schiebetür",
    153: "Schlüssellose Zentralverriegelung",
    154: "Sitzbelüftung",
    155: "Soundsystem",
    156: "Sprachsteuerung",
    157: "Spurhalteassistent",
    158: "Totwinkel-Assistent",
    159: "Touchscreen",
    160: "TV",
    161: "USB",
    162: "Verkehrszeichenerkennung",
    170: "Biodieselumrüstung",
    173: "E10-geeignet",
    174: "Markise",
    187: "360° Kamera",
    189: "Fernlichtassistent",
    190: "Scheinwerferreinigung",
    210: "Sommerreifen",
    211: "Allwetterreifen",
    212: "Stahlfelgen",
    213: "Laserlicht",
    214: "Blendfreies Fernlicht",
    215: "Reserverad",
    216: "Notrad",
    217: "Pannenkit",
    218: "Raucherpaket",
    219: "Ambientebeleuchtung",
    220: "W-Lan / Wifi Hotspot",
    221: "Apple CarPlay",
    222: "Android Auto",
    223: "Induktionsladen für Smartphones",
    224: "Volldigitales Kombiinstrument",
    225: "Innenspiegel automatisch abblendend",
    226: "Gepäckraumabtrennung",
    227: "Geschwindigkeits-begrenzungsanlage",
    228: "Musikstreaming integriert",
    229: "Umklappbarer Beifahrersitz",
    230: "Bi-Xenon Scheinwerfer",
    231: "Winterpaket",
    232: "Abstandswarner",
    233: "Elektrische Sitzeinstellung, hinten",
    237: "Reichweitenverlängerer",
    238: "Spoiler",
    239: "Voll-LED Scheinwerfer",
    240: "Elektronische Parkbremse",
    241: "2-Zonen-Klimaautomatik",
    242: "3-Zonen-Klimaautomatik",
    243: "4-Zonen-Klimaautomatik",
    244: "Schiebetür links",
    245: "Schiebetür rechts",
    248: "Sitzheizung hinten",
    249: "Wärmepumpe",
    250: "Bidirektionales Laden",
    251: "Batteriezertifikat",
}

# Gruppierung für den UI-Picker: [(Gruppenname, [ids...]), ...]
EQUIPMENT_GROUPS = [
    ("Komfort & Klima", [5, 30, 241, 242, 243, 34, 248, 154, 52, 136, 145, 16, 233, 50, 4, 20, 135, 134, 143, 119]),
    ("Assistenz & Sicherheit", [133, 38, 227, 157, 158, 148, 162, 146, 123, 187, 40, 130, 129, 128, 131, 125, 232, 189, 147, 137, 214, 150, 1, 42, 31, 18, 26, 47, 17]),
    ("Multimedia & Konnektivität", [23, 221, 222, 122, 138, 159, 155, 224, 223, 220, 161, 114, 156, 228, 160, 43, 132, 10, 41, 124]),
    ("Licht", [140, 239, 39, 230, 213, 118, 141, 115, 19, 190, 126, 127]),
    ("Antrieb & Fahrwerk", [11, 116, 144, 113, 151, 240, 12, 112, 117]),
    ("Räder & Außenausstattung", [15, 25, 211, 210, 212, 27, 238, 54, 44, 216, 215]),
    ("Elektro/Hybrid", [249, 250, 251, 237]),
    ("Weitere", [45, 219, 36, 3, 170, 173, 13, 139, 121, 2, 226, 225, 29, 46, 6, 142, 174, 149, 217, 218, 48, 152, 244, 245, 153, 32, 111, 21, 28, 229, 231]),
]

VALID_EQUIPMENT_IDS = set(EQUIPMENT.keys())

# Mapping von AutoScout24 Ausstattungs-IDs auf mobile.de fe= URL-Parameter
EQUIPMENT_TO_MOBILE_DE = {
    4: "SUNROOF",
    5: "MANUAL_CLIMATISATION",
    6: "FULL_LEATHER",
    11: "FOUR_WHEEL_DRIVE",
    13: "ELECTRIC_WINDOWS",
    15: "ALLOY_WHEELS",
    16: "ELECTRIC_ADJUSTABLE_SEATS",
    17: "CENTRAL_LOCKING",
    18: "ALARM_SYSTEM",
    19: "FRONT_FOG_LIGHTS",
    20: "TRAILER_COUPLING",
    23: "NAVIGATION_SYSTEM",
    27: "ROOF_RAILS",
    30: "AUTOMATIC_CLIMATISATION",
    34: "ELECTRIC_HEATED_SEATS",
    38: "CRUISE_CONTROL",
    39: "XENON_HEADLIGHTS",
    40: "PARKING_ASSISTANTS",
    41: "ON_BOARD_COMPUTER",
    42: "ESP",
    50: "PANORAMIC_GLASS_ROOF",
    52: "AUXILIARY_HEATING",
    54: "TINTED_WINDOWS",
    112: "SPORT_PACKAGE",
    114: "MULTIFUNCTIONAL_WHEEL",
    116: "SPORT_SUSPENSION",
    117: "SPORT_SEATS",
    122: "BLUETOOTH",
    123: "HEAD_UP_DISPLAY",
    124: "HANDS_FREE_PHONE_SYSTEM",
    125: "ISOFIX",
    126: "LIGHT_SENSOR",
    127: "RAIN_SENSOR",
    128: "PARKING_ASSISTANT_FRONT_SENSORS",
    129: "PARKING_ASSISTANT_REAR_SENSORS",
    130: "REAR_VIEW_CAM",
    131: "PARKING_ASSISTANT_AUTOMATIC_PARKING_SYSTEM",
    133: "ADAPTIVE_CRUISE_CONTROL",
    134: "ARM_REST",
    135: "HEATED_WINDSHIELD",
    136: "HEATED_STEERING_WHEEL",
    137: "HILL_START_ASSIST",
    138: "DAB_RADIO",
    139: "ELECTRIC_TAILGATE",
    140: "LED_HEADLIGHTS",
    141: "LED_RUNNING_LIGHTS",
    142: "LEATHER_STEERING_WHEEL",
    143: "LUMBAR_SUPPORT",
    144: "AIR_SUSPENSION",
    145: "MASSAGE_SEATS",
    146: "FATIGUE_WARNING_SYSTEM",
    147: "NIGHT_VISION_ASSIST",
    148: "EMERGENCY_BRAKE_ASSIST",
    149: "EMERGENCY_CALL_SYSTEM",
    150: "TIRE_PRESSURE_MONITORING",
    151: "PADDLE_SHIFTERS",
    153: "KEYLESS_ENTRY",
    154: "VENTILATED_SEATS",
    155: "SOUND_SYSTEM",
    156: "VOICE_CONTROL",
    157: "LANE_DEPARTURE_WARNING",
    158: "BLIND_SPOT_MONITOR",
    159: "TOUCHSCREEN",
    160: "TV",
    161: "USB",
    162: "TRAFFIC_SIGN_RECOGNITION",
    187: "CAMERA_360",
    189: "HIGH_BEAM_ASSIST",
    190: "HEADLIGHT_WASHER_SYSTEM",
    210: "SUMMER_TIRES",
    211: "ALL_SEASON_TIRES",
    213: "LASER_HEADLIGHTS",
    214: "HIGH_BEAM_ASSIST",
    219: "AMBIENT_LIGHTING",
    220: "WLAN",
    221: "APPLE_CARPLAY",
    222: "ANDROID_AUTO",
    223: "WIRELESS_CHARGING",
    224: "DIGITAL_COCKPIT",
    225: "DIMMING_INTERIOR_MIRROR",
    227: "SPEED_LIMITER",
    228: "INTEGRATED_MUSIC_STREAMING",
    230: "BI_XENON_HEADLIGHTS",
    232: "DISTANCE_WARNING_SYSTEM",
    239: "LED_HEADLIGHTS",
    241: "AUTOMATIC_CLIMATISATION_2_ZONES",
    242: "AUTOMATIC_CLIMATISATION_3_ZONES",
    243: "AUTOMATIC_CLIMATISATION_4_ZONES",
    248: "ELECTRIC_HEATED_REAR_SEATS",
    249: "HEAT_PUMP",
}

# Synonyme / Stichwörter für Text-Nachprüfung (z. B. für Kleinanzeigen)
EQUIPMENT_SYNONYMS: dict[int, list[str]] = {
    4: ["schiebedach", "panoramadach", "glasschiebedach", "hebedach", "panoramaglasdach"],
    5: ["klimaanlage", "klimaautomatik", "klima", "climatronic", "air condition"],
    6: ["leder", "lederausstattung", "ledersitze", "vollleder", "nappa", "leather"],
    11: ["allrad", "4x4", "awd", "4wd", "quattro", "4motion", "xdrive", "dual motor"],
    15: ["alufelgen", "leichtmetallfelgen", "alu-felgen", "lm-felgen", "lm felgen", "alufelge", "leichtmetallräder"],
    16: ["elektrische sitze", "el. sitze", "el. sitzverstellung", "elektrisch verstellbar", "memory-sitze", "sitze elektrisch"],
    20: ["anhängerkupplung", "ahk", "anhängevorrichtung", "anhängerkuppl", "kupplung"],
    23: ["navigation", "navi", "navigationssystem", "discover", "mmi navigation", "professional", "apple carplay", "android auto"],
    30: ["klimaautomatik", "climatronic", "2-zonen", "3-zonen", "automatik-klima", "thermotronic"],
    34: ["sitzheizung", "shz", "sitzhzg", "beheizbare sitze", "beheizte sitze", "winterpaket", "heated seats"],
    38: ["tempomat", "gra", "geschwindigkeitsregelanlage", "cruise control", "abstandstempomat", "acc"],
    39: ["xenon", "bi-xenon", "xenonscheinwerfer"],
    40: ["einparkhilfe", "pdc", "parktronic", "park distance control", "parksensoren", "rückfahrkamera", "kamera", "parkassistent"],
    50: ["panoramadach", "panoramaglasdach", "panoramaschiebedach"],
    52: ["standheizung", "standhzg", "auxiliary heating"],
    114: ["multifunktionslenkrad", "mfl", "lederlenkrad multifunktion", "lenkrad mit multifunktion"],
    123: ["head-up", "headup", "hud", "head up display"],
    130: ["rückfahrkamera", "rfk", "rueckfahrkamera", "rear view", "rückfahr-kamera", "360° kamera", "360 grad kamera", "surround view"],
    133: ["abstandstempomat", "acc", "abstandsregeltempomat", "distronic", "adaptive cruise", "travel assist", "pilot assist", "drive assist", "distance control"],
    135: ["frontscheibe beheizbar", "beheizbare frontscheibe", "frontscheibenheizung"],
    136: ["lenkradheizung", "beheizbares lenkrad", "beheiztes lenkrad", "lenkrad beheizbar"],
    138: ["dab", "dab+", "digitalradio", "digitaler radioempfang"],
    139: ["elektrische heckklappe", "el. heckklappe", "heckklappe elektrisch", "easy open", "virtuelles pedal"],
    140: ["led-scheinwerfer", "led scheinwerfer", "matrix led", "iq.light", "iq light", "led-licht", "voll-led", "laserlicht"],
    145: ["massagesitz", "massagesitze", "massagefunktion", "ergoactive"],
    153: ["keyless", "keyless go", "keyless entry", "kessy", "schlüssellos", "komfortzugang"],
    154: ["sitzbelüftung", "belüftete sitze", "sitzventilation", "klimatisierte sitze"],
    157: ["spurhalteassistent", "lane assist", "spurassistent", "spurverlassenswarnung"],
    158: ["totwinkel", "side assist", "blind spot", "totwinkelassistent", "totwinkel-assistent", "totwinkelwarner"],
    187: ["360° kamera", "360 grad kamera", "surround view", "area view", "rundumkamera", "allview"],
    221: ["apple carplay", "carplay", "apple car play", "app-connect", "smartphone integration"],
    222: ["android auto", "app-connect", "smartphone integration"],
    223: ["induktionsladen", "induktives laden", "wireless charging", "kabelloses laden"],
    224: ["digital cockpit", "virtual cockpit", "volldigital", "digitales kombiinstrument", "widescreen cockpit"],
    249: ["wärmepumpe", "waermepumpe", "heat pump"],
}
